# Backend configuration
backend:
  # Access token required for interacting with the server -- string (empty string for no restrictions)
  accessToken: ""

  # Enable the function to save to a webdav-server (check README for more info) -- boolean
  enableWebdav: false
  
  # Token verification details
  tokenService: "https://us-central1-miranda2.cloudfunctions.net"
  whiteboardToken: "5UVCKlyrstTCCWbg_5PDueGMPY0byaH_Q6OfmEfqDQircePmnX5csaB4d0kziNUj1fYFKa9DJOIx7Tz-xOOrV6GaTWDM-HNJlo1duSyNZOCgtr_NSuaIGpxXF4SjHjIf9F20GnXLDxTlAWGx3TJ2jbqgy1tbWCJ2RLi3kSBOcdvRkq3zz3qA5HfFUSkuQYKrs30hsrsFFtC2I2KJ4fFkc_9FNC0bt4OBBxhDkNoKbPjvaUrJX67Ct84csdmpTZMskUxZ53bMGtR08VV2EYnIFnzfHFSDrq2XU0sK5BXjiz9UkvGgQIezqSWf65cZp6GfRSODUnL09aYSvX7tEiS3lw"

  # Backend performance tweaks
  performance:
    # Whiteboard information broadcasting frequency (in Hz i.e. /s) -- number
    # => diminishing this will result in more latency
    whiteboardInfoBroadcastFreq: 1
    
  # Used in dev mode
  port: 3000

# Frontend configuration
frontend:
  # When a whiteboard is loaded on a client
  onWhiteboardLoad:
    # should an (editable) whiteboard be started in read-only mode by default -- boolean
    setReadOnly: false

    # should the whiteboard info be displayed by default -- boolean
    displayInfo: false

  # Show the smallest screen indicator ? (with dotted lines) -- boolean
  showSmallestScreenIndicator: true

  # Image download format, can be "png", "jpeg" (or "webp" -> only working on chrome) -- string
  imageDownloadFormat: "png"

  # Frontend performance tweaks
  performance:
    # Refresh frequency of the debug / info div (in Hz i.e. /s) -- number
    refreshInfoFreq: 5

    # Throttling of pointer events (except drawing related) -- array of object (one must have fromUserCount == 0)
    # Throttling of events can be defined for different user count levels
    # Throttling consist of skipping certain events (i.e. not broadcasting them to others)
    pointerEventsThrottling:
      - # User count from which the specific throttling is applied -- number
        fromUserCount: 0
        # Min screen distance (in pixels) below which throttling is applied
        minDistDelta: 1
        # Maximum frequency above which throttling is applied
        maxFreq: 30
      - fromUserCount: 10
        minDistDelta: 5
        maxFreq: 10

  # Path to access the blackboard
  URLPrefix: "/buzzboard"

  # Port to serve the blackboard
  port: 8080